### ISSUE TITLE
Visualize found blocks and payouts in a way similar to shares/uncles

### ISSUE THREAD

**Issue by hbs** [WeebDataHoarder/p2pool-log#4]
The timeline of shares and uncles is really nice, but it would be even nicer if the found blocks and actual payouts were visualized in a similar manner. on timelines above or below the two existing ones.

Something like:

```
Shares in last day
[<...........................................1..................................1...........|......1.......................<]
Uncles in last day
[<..........................................................................................|..............................<]
Blocks in last day
[<..1...............................1................................................1......|..............................<]
Payouts in last day
[<..................................1................................................1......|..............................<]
```

**Comment by WeebDataHoarder** [comment]
I think for the Observer this is at least implemented on the miner page except the "blocks last day". This repository is being archived in favor of https://git.gammaspectra.live/P2Pool/p2pool-observer so if this feature request is still valid please open an issue there (or come around IRC)
