### ISSUE TITLE
missing README.md

### ISSUE THREAD

**Issue by jahway603** [WeebDataHoarder/p2pool-log#5]
This repo is missing a README.md with a brief description of what it logs for a p2pool

**Comment by jahway603** [comment]
Created PR https://github.com/WeebDataHoarder/p2pool-log/pull/6 to have a basic README.me.

**Comment by WeebDataHoarder** [comment]
Now covered under https://git.gammaspectra.live/P2Pool/p2pool-observer (and has README!)
